[mgr]
show_hidden = true

[opener]
play = [{ run = 'iina "$@"', block = true, for = "macos" }]
edit = [
  { run = 'nvim "$@"', block = true },
  { run = 'marktext -n "$@"', orphan = true },
  { run = 'code "$@"', orphan = true },
  { run = 'zed "$@"', orphan = true },
]
extract = [
  { run = 'ouch d -y %*', desc = "Extract here with ouch", for = "windows" },
  { run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]
open = [{ run = "open %s1", desc = "Open" }]

[open]
prepend_rules = [
  { url = "*.json", use = "edit" },
  { url = "*.html", use = [
    "open",
    "edit",
  ] },
]

[plugin]
prepend_fetchers = [
  { id = "git", group = "fetcher", url = "*", run = "git" },
  { id = "git", group = "fetcher", url = "*/", run = "git" },
]

append_previewers = [{ mime = "*", run = "hexyl" }]
