[mgr]
show_hidden = true

[opener]
play = [{ run = 'iina "$@"', block = true, for = "macos" }]
edit = [
  { run = 'nvim "%s1"', block = true },
  { run = 'code "%s1"', orphan = true },
  { run = 'zed "%s1"', orphan = true },
  { run = '/Applications/MarkText.app/Contents/MacOS/MarkText "%s1"', orphan = true, for = "macos", desc = "MarkText" },
]
extract = [
  { run = 'ouch d -y "%s1"', desc = "Extract here with ouch", for = "unix" },
]
open = [{ run = "open %s1", desc = "Open" }]

[open]
prepend_rules = [
  { url = "*.json", use = "edit" },
  { url = "*.html", use = [
    "open",
    "edit",
  ] },
]

[plugin]
prepend_fetchers = [
  { id = "git", group = "fetcher", url = "*", run = "git" },
  { id = "git", group = "fetcher", url = "*/", run = "git" },
]

append_previewers = [{ mime = "*", run = "hexyl" }]
